version: "3.8"

services:
  backend:
    container_name: backend
    build: ./
    restart: always
    ports:
      - "4001:4001"
    volumes:
      - .:/app
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
